### PR TITLE
refactor: improved dx, typed library, comments

### PR DESCRIPTION
**Pull request by a-rustacean**
I refactored the code, improved the readme, eliminated the deprecated `request` dependency, introduced `axios` due to its larger community, incorporated JSDoc comments, eliminated unnecessary recursion, utilized modern and efficient language features like `Promise.all`, excluded `node_modules` as it's not necessary for npm, provided a custom domain option for `TempMail` (#7 was unnecessary), and introduced `eslint`, `prettier`, `husky`, `lint-staged`, and `npm-scripts` to enhance the developer experience.

### CODE REVIEW

**Comment by Jon-Becker** [comment]
Hey! I got your email. I don't check this repository too often for PRs, but I will in the future.

I'll review this today and merge it in if all is well. I'll also probably set up a test suite, and add other services so that the library works with more than one temp mail service. 

Thank you for your contribution, I appreciate it!

**Review by Jon-Becker — CHANGES_REQUESTED** [review]
Looks good, but please don't remove `preview.png`, its used by some external services I believe. I can make the npm module ignore it though.

I'll also make a few changes here before merging.

**Comment by a-rustacean** [comment]
Certainly, I've readded the `preview.png` file as per your request. Thank you for your quick response and assistance!

**Comment by a-rustacean** [comment]
Could you kindly review the changes I've made?

**Comment by Jon-Becker** [comment]
i'll make a release after testing thoroughly :)

if you would like to be made a contributor here, since I don't manage this repo much, let me know!

**Comment by a-rustacean** [comment]
I'd be happy to be a contributor.

**Pull request merged**
